#!/usr/bin/python3
import sys
""" Log parsing Module. """

# <IP Address> - [<date>] "GET /projects/260 HTTP/1.1" <status_code> <file_size>
filename = "file.txt"
n_line = 0
# Handle inputs first
while n_line <= 10:
    file_size = sys.argv[-1]
    total_size = 0
    count = []
    status_code = sys.argv[-2]
    status_codes = [200, 301, 400, 401, 403, 404, 405, 500]
    for idx, status in enumerate(status_codes):
        if status[idx] == status_code[idx]:
            count[idx] += 1
    total_size += int(file_size)
    if KeyboardInterrupt:
        break

with open(filename, "a+") as file:
    file.read()
    inputs = f"File size: {total_size}"
    file.write(inputs)
    file.write(f"{sys.argv[-2]}: {count}")
    file.seek(0)
    print(file.read())

with open(filename, "a+") as file:
    for line in sorted(file):
        print(f"{status_code}: {count}")
